version: '3'
services:
  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - SERVER_IP=server
      - SERVER_CONFIG_FILE=/config/initialConfig.yaml
    volumes:
      - server-vol:/config
    networks:
      - testing_net

  client1:
    container_name: client1
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_SERVER_ADDRESS=server:12345
      - CLI_CONFIG_FILE=/config/initialConfig.yaml
    volumes:
      - client-vol:/config
    networks:
      - testing_net
    depends_on:
      - server

  client2:
    container_name: client2
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=2
      - CLI_SERVER_ADDRESS=server:12345
      - CLI_CONFIG_FILE=/config/initialConfig.yaml
    volumes:
      - client-vol:/config
    networks:
      - testing_net
    depends_on:
      - server

volumes:
  server-vol:
    driver: local
    driver_opts:
      type: none
      device: $PWD/server/config
      o: bind
  client-vol:
    driver: local
    driver_opts:
      type: none
      device: $PWD/client/config
      o: bind

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24